<a href="https://colab.research.google.com/github/sandhiyasudha/machine-learning-project-sandhiya/blob/main/machine_learning_health.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving cardioActivities.csv to cardioActivities.csv

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use("ggplot")

In [ ]:
df = pd.read_csv("cardioActivities.csv")
df.columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 508 entries, 0 to 507
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date                      508 non-null    object
 1   Activity Id               508 non-null    object
 2   Type                      508 non-null    object
 3   Route Name                1 non-null      object
 4   Distance (km)             508 non-null    float64
 5   Duration                  508 non-null    object
 6   Average Pace              508 non-null    object
 7   Average Speed (km/h)      508 non-null    float64
 8   Calories Burned           508 non-null    float64
 9   Climb (m)                 508 non-null    int64
 10  Average Heart Rate (bpm)  294 non-null    float64
 11  Friend's Tagged           0 non-null      float64
 12  Notes                     231 non-null    object
 13  GPX File                  504 non-null    object
dtypes: float64(5), int64(1), object(8)
memory usage: 55.7+ KB

In [ ]:
df.columns

Index(['Date', 'Activity Id', 'Type', 'Route Name', 'Distance (km)',
       'Duration', 'Average Pace', 'Average Speed (km/h)', 'Calories Burned',
       'Climb (m)', 'Average Heart Rate (bpm)', 'Friend's Tagged', 'Notes',
       'GPX File'],
      dtype='object')

In [ ]:
df.describe()

,Distance (km),Average Speed (km/h),Calories Burned,Climb (m),Average Heart Rate (bpm),Friend's Tagged
count,508.000000,508.000000,5.080000e+02,508.00000,294.000000,0.0
mean,11.757835,11.341654,1.878197e+04,128.00000,143.530612,NaN
std,6.209219,2.510516,2.186930e+05,108.52604,10.583848,NaN
min,0.760000,1.040000,4.000000e+01,0.00000,77.000000,NaN
25%,7.015000,10.470000,4.917500e+02,53.00000,140.000000,NaN
50%,11.460000,11.030000,7.280884e+02,92.00000,144.000000,NaN
75%,13.642500,11.642500,9.212500e+02,172.25000,149.000000,NaN
max,49.180000,24.330000,4.072685e+06,982.00000,172.000000,NaN

In [ ]:
df.isnull().sum()

Date                          0
Activity Id                   0
Type                          0
Route Name                  507
Distance (km)                 0
Duration                      0
Average Pace                  0
Average Speed (km/h)          0
Calories Burned               0
Climb (m)                     0
Average Heart Rate (bpm)    214
Friend's Tagged             508
Notes                       277
GPX File                      4
dtype: int64