In [ ]:
from google.colab import files
uploaded = files.upload()

Saving tamilmusic_directors_toptracks.csv to tamilmusic_directors_toptracks.csv

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
af = pd.read_csv("tamilmusic_directors_toptracks.csv")

In [ ]:
new_af = af.copy()

In [ ]:
print("\n1. Random Records")
display(new_af.sample(5))

1. Random Records

,artist_name,track_name,popularity,duration_ms,album,release_date,collaborating_artist,explicit,number_of_markets,available_markets
36,Harris Jayaraj,Ennamo Yeadho,61,333600,KO (Original Motion Picture Soundtrack),2011-01-17,Aalaap Raju,False,NaN,NaN
3,Ilayaraja,"Nila Kayuthu Neram Nalla Neram (From ""Sakalaka...",47,272760,Iravin Sorgam,2024-07-19,Vaali,False,NaN,NaN
68,Santhosh Narayanan,"Mainaru Vetti Katti (From ""Dasara"")",28,203052,"Mainaru Vetti Katti (From ""Dasara"") - Single",2023-03-10,Dhee,False,NaN,NaN
15,A.R. Rahman,Kun Faya Kun,71,470500,Rockstar,2011-10-01,Javed Ali,False,NaN,NaN
113,Devi Sri Prasad,Uppenantha,64,327640,Aarya - 2 (Original Motion Picture Soundtrack),2009-10-30,KK,False,NaN,NaN

In [ ]:
print("\n2. First 5 Records")
display(new_af.head())

2. First 5 Records

,artist_name,track_name,popularity,duration_ms,album,release_date,collaborating_artist,explicit,number_of_markets,available_markets
0,Ilayaraja,"Ooru Sanam Thoongidichu (From ""Mella Thirandha...",19,278400,Ilayaraja Love bites,2023-07-13,S. Janaki,False,NaN,NaN
1,Ilayaraja,"Oru Naalum (From ""Ejjaman"" )",2,359026,Ilayaraja Love Beats,2023-07-13,Vaali,False,NaN,NaN
2,Ilayaraja,"Aalappol Velappol (From ""Ejjaman"" )",1,304848,Ilayaraja Love Beats,2023-07-13,Vaali,False,NaN,NaN
3,Ilayaraja,"Nila Kayuthu Neram Nalla Neram (From ""Sakalaka...",47,272760,Iravin Sorgam,2024-07-19,Vaali,False,NaN,NaN
4,Ilayaraja,Naanaga Naanillai Thaye (Version 1),48,272493,Thoongathe Thambi Thoongathe (Original Motion ...,2024-01-05,Vaali,False,NaN,NaN